# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('birthDate', models.CharField(max_length=200)),
            ],
        ),
    ]
