# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-06 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ganenetPage', '0003_save'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='review',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
