# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-06 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganenetPage', '0004_auto_20210506_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='submission_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
