# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganenetPage', '0005_review_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myinfo',
            name='birthDate',
            field=models.DateTimeField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='review',
            name='submission_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
