# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-31 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kid',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name=b'birthday')),
                ('favoriteColor', models.CharField(max_length=200)),
                ('favoriteAnimal', models.CharField(max_length=200)),
                ('siblingsNumber', models.IntegerField(default=0)),
                ('parentName', models.CharField(max_length=200)),
                ('parentPhone', models.CharField(max_length=200)),
                ('parentEmail', models.CharField(max_length=200)),
            ],
        ),
    ]
