# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('nameSubject', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('songs', models.CharField(max_length=2000)),
                ('selfTasks', models.CharField(max_length=2000)),
                ('submissions', models.FileField(upload_to=b'submissionsTasks')),
            ],
        ),
    ]
