# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjecttest',
            fields=[
                ('nameSubject', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='kid',
            name='birth_date',
            field=models.DateTimeField(verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='submissions',
            field=models.FileField(upload_to='submissionsTasks'),
        ),
    ]
