# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-11 13:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_auto_20210411_1649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subjecttest',
        ),
    ]
