# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-16 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_auto_20210412_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meeting_text', models.CharField(max_length=2000)),
            ],
        ),
    ]
