# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0007_auto_20210416_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('titel', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('ticket_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
