# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ticket_date',
            field=models.DateTimeField(),
        ),
    ]
