# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-21 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0009_auto_20210422_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='ticket_date',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
