# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_auto_20210422_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('nameSubmission', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
