# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-25 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0011_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title',
        ),
    ]
