# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-06 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0012_auto_20210425_1901'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
