# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0014_reportbug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportbug',
            name='bugDes',
        ),
        migrations.AddField(
            model_name='reportbug',
            name='emailAddress',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbug',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbug',
            name='lastName',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbug',
            name='message',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AddField(
            model_name='reportbug',
            name='phoneNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportbug',
            name='subject',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
