# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-23 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0015_auto_20210510_0010'),
        ('homePage', '0015_auto_20210514_0938'),
    ]

    operations = [
    ]
