# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-23 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0016_merge_20210523_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('birth_date', models.DateTimeField(verbose_name=b'birthday')),
                ('parentPhone', models.CharField(max_length=200)),
                ('parentEmail', models.CharField(max_length=200)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.kid')),
            ],
        ),
    ]
