# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-23 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0016_merge_20210523_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='mashov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.IntegerField(default=-1)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.kid')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homePage.subject')),
            ],
        ),
    ]
