# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0017_mashov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('emailAddress', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=500)),
                ('message', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
