# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0017_parent'),
        ('homePage', '0018_message'),
    ]

    operations = [
    ]
