# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0019_merge_20210528_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashov',
            name='kid',
        ),
        migrations.AlterField(
            model_name='mashov',
            name='feedback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parent',
            name='birth_date',
            field=models.DateTimeField(verbose_name='birthday'),
        ),
    ]
