# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0020_auto_20210528_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
