# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0020_auto_20210529_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashov',
            name='feedback',
            field=models.IntegerField(default=-1),
        ),
    ]
