# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0021_auto_20210528_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
