# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-28 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0022_auto_20210528_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='user',
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
