# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-29 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0024_auto_20210529_1417'),
    ]
