# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-29 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0026_auto_20210529_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashov',
            name='v1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mashov',
            name='v2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mashov',
            name='v3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mashov',
            name='v4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mashov',
            name='v5',
            field=models.IntegerField(default=0),
        ),
    ]
