pipeline {
    agent none
    stages{
        stage('Build'){
            agent{
                docker{
                    image 'python:3.6'
                }
            }
            steps{
                withEnv(["HOME=${env.WORKSPACE}"]){
                    sh 'python -m pip install django'
                    sh 'python -m py_compile manage.py'
                }
            }
        }
    }
}
