pipeline {
    agent { docker { image 'python:2.7.13' } }
    stages {
        stage('runserver') {
            steps {
                sh 'sudo python3.6 manage.py runserver'
            }
        }
    }
}
