# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parentsPage', '0006_auto_20210411_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportBug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugDes', models.CharField(max_length=5000)),
            ],
        ),
    ]
