# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-14 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parentsPage', '0007_reportbug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reportBug',
        ),
    ]
